name: 'Upload Release'
description: 'Uploads a built release file'
inputs:
  artifact_name:
    description: 'artifact name'
    required: true
  source:
    required: false
    type: string
    default: 'package'
runs:
  using: "composite"
  steps:
    - name: Save artifact
      uses: actions/upload-artifact@master
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ runner.temp }}/shadow_build_dir/${{ inputs.source }}/${{ inputs.artifact_name }}
